language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-android-m2repository
notifications:
  email:
    - matej.bobek@student.tuke.sk
